In [1]:
import torch
from src.EuroSat_dataloaders import transformation_eurosat

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from torchvision.datasets import EuroSAT
from torchvision.transforms import v2
from torch.utils.data import Dataset,DataLoader

ds = EuroSAT("../EuroSat",download=False)


c:\Users\nikos\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\datapoints\__init__.py:12: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
c:\Users\nikos\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\transforms\v2\__init__.py:54: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback

In [15]:

transforms = v2.Compose([
    v2.ToTensor(),
    v2.ToDtype(torch.float32),
    v2.Normalize(mean=[ 87.31588889,  96.47403704, 103.47966667], std=[22.79411111, 16.10118519, 13.59133333]),
    v2.Resize(224),
])
# ds = EuroSAT("../EuroSat",transform=transforms,download=False)

c:\Users\nikos\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\transforms\v2\_deprecated.py:41: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `transforms.Compose([transforms.ToImageTensor(), transforms.ConvertImageDtype()])`.
  warnings.warn(


In [16]:
ds = EuroSAT("../EuroSat",transform=transforms,target_transform=transformation_eurosat,download=False)
dataloader = DataLoader(dataset=ds, batch_size=32,shuffle=True,num_workers=4, pin_memory_device='cuda:0')


In [5]:
from src.EuroSat_dataloaders import Test_Dataset_EuroSat, Train_Dataset_EuroSat 
transforms = v2.Compose([
    v2.ToTensor(),
    v2.ToDtype(torch.float32),
    v2.Resize(224,antialias=None),
])
ds = EuroSAT("../EuroSat",transform=transforms,target_transform=transformation_eurosat,download=False)
ds_test = Test_Dataset_EuroSat(ds)
ds_train = Train_Dataset_EuroSat(ds)

c:\Users\nikos\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\transforms\v2\_deprecated.py:41: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `transforms.Compose([transforms.ToImageTensor(), transforms.ConvertImageDtype()])`.
  warnings.warn(


In [10]:
import tqdm
mean_channels = [0,0,0]
std_channels = [0,0,0]
for j in range(3):
    for i,tq in zip(range(len(ds_test)),tqdm.tqdm(range(1,len(ds_test)+1))):
        mean_channels[j] += ds_test[i][0][j].mean().float()
        std_channels[j] += ds_test[i][0][j].std().float()
print(np.array(std_channels)/(len(ds_test)))
print(np.array(mean_channels)/(len(ds_test)))
for j in range(3):
    for i,tq in zip(range(len(ds_train)),tqdm.tqdm(range(1,len(ds_train)+1))):
        mean_channels[j] += ds_train[i][0][j].mean().float()
        std_channels[j] += ds_train[i][0][j].std().float()
print(np.array(std_channels)/(len(ds_test)+len(ds_train)))
print(np.array(mean_channels)/(len(ds_test)+len(ds_train)))

100%|█████████▉| 5399/5400 [00:09<00:00, 574.19it/s]


[0.17722037 0.12389518 0.10415525]
[-0.31044433 -0.23938923 -0.18359716]


100%|█████████▉| 21599/21600 [00:37<00:00, 577.65it/s]

[0.1768554  0.12416639 0.1041581 ]
[-0.31124905 -0.23941825 -0.18445934]
